platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: movies-service

outputs:
- name: package-output

run:
  path: movies-service/ci/tasks/package.sh
